
language: objective-c
osx_image: xcode7
before_install:
- gem install xcpretty --no-document
script:
# - set -o pipefail && xcodebuild -project WCCircularFloatingActionMenu.xcodeproj -scheme WCCircularFloatingActionMenu -sdk macosx test | xcpretty -c
# - set -o pipefail && xcodebuild -project WCCircularFloatingActionMenu.xcodeproj -scheme WCCircularFloatingActionMenu -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- pod lib lint
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true